#!/usr/bin/perl
use warnings;
use strict;

my $root = "/home/deb-record";
my $edge = "-"x80;

my $flag = $ARGV[0];
my $name = $ARGV[1];

unless($flag){
	print "use option -inst or -del\n";
	exit;
}

unless($flag eq '-inst' or $flag eq '-del'){
	print "wrong option, use -inst or -del\n";
	exit;
}


unless($name)
{
	print "Please select a <name>\n";
	exit;
}

my $filename;

if($flag eq '-inst'){
	opendir PATH, "$root/installed"
		or die "Cannot opendir $root/installed: $!";
	my @files = readdir PATH;
	closedir PATH;
	for my $file (@files){
		next if $file eq '.' or $file eq '..';
		my $tmpfile = $file;
		$tmpfile =~ s/_\[\d+-\d+-\d+\]$//;
		if($name eq $tmpfile){
			$filename = "$root/installed/$file";
			last;
		}
	}
}

if($flag eq '-del'){
	opendir PATH, "$root/deleted"
		or die "Cannot opendir $root/deleted: $!";
	my @files = readdir PATH;
	closedir PATH;
	for my $file (@files){
		next if $file eq '.' or $file eq '..';
		my $tmpfile = $file;
		$tmpfile =~ s/_\[\d+-\d+-\d+\]$//;
		if($name eq $tmpfile){
			$filename = "$root/deleted/$file";
			last;
		}
	}
}

unless($filename){
	if($flag eq '-inst'){
		print "$edge\n";
		print "File \"$name"."_[XXXX_XX_XX] isn't in \$root/installed/\n";
		print "$edge\n";
		exit;
	}
	if($flag eq '-del'){
		print "$edge\n";
		print "File \"$name"."_[XXXX_XX_XX] isn't in \$root/deleted/\n";
		print "$edge\n";
		exit;
	}
}

open my $hf, '<', $filename;
my $content = <$hf>;

print "$content\n";

close $hf;

