#!/usr/bin/perl
use warnings;
use strict;
use File::Basename;

my $root = "/home/deb-record";
my $edge = "-"x80;

my $name = $ARGV[0];
my $content = $ARGV[1];

unless($name){
	print "LOST: filename\ndeb-add <filename> \"contents\"\n";
	exit;
}

unless($content){
	print "LOST: contents\ndeb-add <filename> \"contents\"\n";
	exit;
}

$content =~ s/\n/ /g;
$content =~ s/ +/ /g;

my ($sec, $min, $hour, $day, $mon, $year, $wday, $yday, $isdst) = localtime time;
my $yearn = $year + 1900;
my $monn = $mon + 1;
my $dayn = $day + 0;
my $date = "$yearn-$monn-$dayn";


opendir PATH,"$root/installed" or die "Cannot opendir $root/installed: $!";
my @filenames = readdir PATH;
closedir PATH;
for my $filename (@filenames) {
	next if $filename eq '.' or $filename eq '..';
	my $tmpname = $filename;
	$tmpname =~ s/_\[\d+-\d+-\d+\]$//;
	if($name eq $tmpname){
		print $edge."\n";
		print "File \"$filename\" is already in \$root/installed\n";
		print $edge."\n";
		exit;
	}
}

opendir PATH,"$root/deleted" or die "Cannot opendir $root/deleted: $!";
@filenames = readdir PATH;
closedir PATH;
for my $filename (@filenames) {
	next if $filename eq '.' or $filename eq '..';
	my $tmpname = $filename;
	$tmpname =~ s/_\[\d+-\d+-\d+\]$//;
    if($name eq $tmpname){
		print $edge."\n";
		print "File \"$filename\" is already in \$root/deleted\n";
		print $edge."\n";
		exit;
	}
}

my $file = "$root/installed/$name"."_[$date]";
open my $fh, '>', $file
	or die "Could not open $root/$name: $!";
print $fh $content;
close $fh;

my $basename = basename $file;

print "$edge\n";
print "$content \nwrited to \"\$root/installed/$basename\"\n";
print "$edge\n";
